'clips': ''
'clips_folder': 'D:\\Dropbox (UCL - SWC)\\Dropbox (UCL - SWC)\\Rotation_vte\\data\\z_TrialVideos'
dlc_network_posecfg: 'C:\Users\Federico\Documents\GitHub\DeepLabCut\pose-tensorflow\models\Maze06Sept-trainset95shuffle1\test'
'dlc_network_snapshot': 'C:\Users\Federico\Documents\GitHub\DeepLabCut\pose-tensorflow\models\maze06Sept-trainset95shuffle1\train\snapshot-1030000'
'scorer': 'DeepCut_resnet50_FC_1030000'
'store trial videos': True
